import { useLayoutEffect, useRef, useState, useEffect } from "react";
import { css } from "@linaria/core";
import { faker } from "@faker-js/faker";
import TextEditor from "../components/datagrid/editors/textEditor";
import DataGrid from "../components/datagrid/DataGrid";

const columns = [
  {
    field: "SerialN",
    headerName: "SerialN",
    toolTip: true,
    resizable: true,
  },
  {
    field: "document",
    headerName: "Document Full Name",
    toolTip: true,
  },
  {
    field: "DocumentArea",
    headerName: "DocumentArea",
    toolTip: true,
  },
  {
    field: "AREAID",
    headerName: "AREAID",
    toolTip: true,
  },
  {
    field: "PartyName",
    headerName: "PartyName",
    toolTip: true,
  },
  {
    field: "UploadedOn",
    headerName: "UploadedOn",
    toolTip: true,
  },
  {
    field: "uploadeddocumentsid",
    headerName: "uploadeddocumentsid",
    toolTip: true,
  },
  {
    field: "Documentname",
    headerName: "Documentname",
    toolTip: true,
  },
  {
    field: "Documentpath",
    headerName: "Documentpath",
    toolTip: true,
  },
];

function createRows(numberOfRows) {
  const rows = [];

  for (let i = 0; i < numberOfRows; i++) {
    rows[i] = {
      id: `id_${i}`,
      title: faker.name.prefix(),
      firstName: faker.name.firstName(),
      lastName: faker.name.firstName(),
      email: faker.internet.email(),
      phone: faker.phone.number(),
    };
  }

  return rows;
}

export default function Demo({ direction }) {
  const [rows, setRows] = useState(createRows(100));
  const [isLoading, setIsLoading] = useState(false);
  const gridRef = useRef(null);

  return (
    <>
      <DataGrid
        columnData={columns}
        rowData={samRow}
        innerRef={gridRef}
        serialNumber={true}
        selection={true}
        columnWidthEqually={true}
        // rowHeight={50}
      />
    </>
  );
}
const samRow = [
  {
    SerialN: 1,
    Stafftype: null,
    document: "TableData (10).pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "ANUSHWETA BALSRAF(SWP60167)",
    UploadedOn: "11-Dec-2023 11:41:15",
    Unreadcount: 0,
    uploadeddocumentsid: 380,
    Ismustread: false,
    PartyTypeID: 2,
    Documentname: "Test05Dec12",
    ROLEID: 2,
    Documentpath: "Admin/Mid Area/ATCSO/M3     ",
  },
  {
    SerialN: 2,
    Stafftype: null,
    document: "The basic form of administrative punishment ar.pdf",
    DocumentArea: "Group Memos",
    AREAID: 7,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "11-Dec-2023 10:29:18",
    Unreadcount: 6,
    uploadeddocumentsid: 458,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "G Test-0112 Unicode standard solves the encoding-1",
    ROLEID: 1,
    Documentpath: "Admin/GROUPMEMOS/undefined",
  },
  {
    SerialN: 3,
    Stafftype: null,
    document:
      "The basic form of administrative punishment are warning fine arrest corrective labor temporary deprivation of special rights governed by a three-month.pdf",
    DocumentArea: "Group Memos",
    AREAID: 7,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "11-Dec-2023 10:15:59",
    Unreadcount: 6,
    uploadeddocumentsid: 457,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "G Test-0111",
    ROLEID: 1,
    Documentpath: "Admin/GROUPMEMOS/",
  },
  {
    SerialN: 4,
    Stafftype: null,
    document: "Cab Control Air Flight Menu Bar 110.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "11-Dec-2023 10:14:53",
    Unreadcount: 1,
    uploadeddocumentsid: 456,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "P Test-0112",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/996",
  },
  {
    SerialN: 5,
    Stafftype: null,
    document:
      "The basic form of administrative punishment are warning fine arrest corrective labor temporary deprivation of special rights governed by a three-month.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "11-Dec-2023 10:13:24",
    Unreadcount: 1,
    uploadeddocumentsid: 455,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "P Test-011",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/996",
  },
  {
    SerialN: 6,
    Stafftype: null,
    document: "TableData (10).pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "ANUSHWETA BALSRAF(SWP60167)",
    UploadedOn: "11-Dec-2023 10:07:08",
    Unreadcount: 0,
    uploadeddocumentsid: 454,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Test011Dec M5 atco",
    ROLEID: 2,
    Documentpath: "Admin/Mid Area/ATCO/M5     ",
  },
  {
    SerialN: 7,
    Stafftype: 0,
    document: "TableData (11).pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "ANUSHWETA BALSRAF(SWP60167)",
    UploadedOn: "11-Dec-2023 10:04:29",
    Unreadcount: 0,
    uploadeddocumentsid: 453,
    Ismustread: false,
    PartyTypeID: 2,
    Documentname: "Test11Dec M4 atcso",
    ROLEID: 2,
    Documentpath: "Admin/Mid Area/ATCSO/M4     ",
  },
  {
    SerialN: 8,
    Stafftype: 0,
    document: "Air_Control_110.pdf",
    DocumentArea: "Group Memos",
    AREAID: 7,
    PartyName: "NIKHIL HEDUKAR(SWP60164)",
    UploadedOn: "11-Dec-2023 09:27:59",
    Unreadcount: 3,
    uploadeddocumentsid: 421,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "G Test-11-071",
    ROLEID: 1,
    Documentpath: "Admin/GROUPMEMOS/",
  },
  {
    SerialN: 9,
    Stafftype: null,
    document: "Test 4.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "NIKHIL HEDUKAR(SWP60164)",
    UploadedOn: "11-Dec-2023 08:31:46",
    Unreadcount: 0,
    uploadeddocumentsid: 340,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "DD2",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/atcotestfolder",
  },
  {
    SerialN: 10,
    Stafftype: null,
    document: "",
    DocumentArea: "Web Links",
    AREAID: 3,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "11-Dec-2023 07:14:57",
    Unreadcount: 0,
    uploadeddocumentsid: 451,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "LAI",
    ROLEID: 1,
    Documentpath: "www.laminaarin",
  },
  {
    SerialN: 11,
    Stafftype: null,
    document: "www.gmail.com",
    DocumentArea: "Web Links",
    AREAID: 3,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "11-Dec-2023 07:14:57",
    Unreadcount: 0,
    uploadeddocumentsid: 431,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Gmail",
    ROLEID: 1,
    Documentpath: "www.gmail.com",
  },
  {
    SerialN: 12,
    Stafftype: null,
    document: "A319 MANUAL - Copy (2).pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "11-Dec-2023 05:45:36",
    Unreadcount: 0,
    uploadeddocumentsid: 448,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "hgkhkkgkk",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/folder2",
  },
  {
    SerialN: 13,
    Stafftype: null,
    document: "AAAA CONTINUING.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "11-Dec-2023 05:45:36",
    Unreadcount: 0,
    uploadeddocumentsid: 449,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "kghkkkgkkgkkjk",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/folder2",
  },
  {
    SerialN: 14,
    Stafftype: null,
    document: "A20.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "11-Dec-2023 05:45:36",
    Unreadcount: 0,
    uploadeddocumentsid: 450,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "hghghfhhhh",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/folder2",
  },
  {
    SerialN: 15,
    Stafftype: null,
    document: "DPP PLAN.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "Admin R(AD001)",
    UploadedOn: "11-Dec-2023 05:31:06",
    Unreadcount: 0,
    uploadeddocumentsid: 347,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "F1",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/caas files",
  },
  {
    SerialN: 16,
    Stafftype: null,
    document: "Information Technology Act 2000.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "Admin R(AD001)",
    UploadedOn: "11-Dec-2023 05:31:06",
    Unreadcount: 0,
    uploadeddocumentsid: 348,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "F2",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/caas files",
  },
  {
    SerialN: 17,
    Stafftype: null,
    document: "Digital Personal Data Protection Act AUG 2023.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "Admin R(AD001)",
    UploadedOn: "11-Dec-2023 05:31:06",
    Unreadcount: 0,
    uploadeddocumentsid: 349,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "F3",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/caas files",
  },
  {
    SerialN: 18,
    Stafftype: null,
    document: "LAI TSP NG Program Charter.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "Admin R(AD001)",
    UploadedOn: "11-Dec-2023 05:31:06",
    Unreadcount: 0,
    uploadeddocumentsid: 350,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "F4",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/caas files",
  },
  {
    SerialN: 19,
    Stafftype: null,
    document: "Air Control _21-08-2020.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "11-Dec-2023 04:47:58",
    Unreadcount: 0,
    uploadeddocumentsid: 447,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "P Test 11",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/1004",
  },
  {
    SerialN: 20,
    Stafftype: null,
    document: "Air_Control_110.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 12:20:01",
    Unreadcount: 0,
    uploadeddocumentsid: 446,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "P Test-081",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/996",
  },
  {
    SerialN: 21,
    Stafftype: null,
    document: "www.laminaar.com",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "NIKHIL HEDUKAR(SWP60164)",
    UploadedOn: "08-Dec-2023 11:17:39",
    Unreadcount: 0,
    uploadeddocumentsid: 444,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "LAI_Portal-Link-",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M2     ",
  },
  {
    SerialN: 22,
    Stafftype: null,
    document: "art_work02-9.5MB_new.pdf",
    DocumentArea: "Info Notice",
    AREAID: 2,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 11:09:06",
    Unreadcount: 754,
    uploadeddocumentsid: 184,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Info test-031 new",
    ROLEID: 1,
    Documentpath: "Admin/Info Notice/ATCO/Notams_test-04 /",
  },
  {
    SerialN: 23,
    Stafftype: null,
    document: "Test10MB_Oct.txt",
    DocumentArea: "Info Notice",
    AREAID: 2,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 11:09:06",
    Unreadcount: 0,
    uploadeddocumentsid: 185,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Info test-032 new",
    ROLEID: 1,
    Documentpath: "Admin/Info Notice/ATCO/Notams_test-04 /",
  },
  {
    SerialN: 24,
    Stafftype: null,
    document: "TableData.pdf",
    DocumentArea: "Info Notice",
    AREAID: 2,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 11:09:06",
    Unreadcount: 100,
    uploadeddocumentsid: 268,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "test1",
    ROLEID: 1,
    Documentpath: "Admin/Info Notice/ATCO/Notams_test-04 /",
  },
  {
    SerialN: 25,
    Stafftype: null,
    document: "TSP (1).pdf",
    DocumentArea: "Info Notice",
    AREAID: 2,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 11:09:06",
    Unreadcount: 753,
    uploadeddocumentsid: 269,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "test2",
    ROLEID: 1,
    Documentpath: "Admin/Info Notice/ATCO/Notams_test-04 /",
  },
  {
    SerialN: 26,
    Stafftype: null,
    document: "24-51-10REV02.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "NILESH TYADE ATCSO(SWP60169)",
    UploadedOn: "08-Dec-2023 11:00:04",
    Unreadcount: 1,
    uploadeddocumentsid: 445,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Tayde SWP PM test 08 DEC",
    ROLEID: 2,
    Documentpath: "ADMIN/PERSONALMEMOS/988",
  },
  {
    SerialN: 27,
    Stafftype: null,
    document: "Cab Control 103.pdf",
    DocumentArea: "Info Notice",
    AREAID: 2,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:59:11",
    Unreadcount: 0,
    uploadeddocumentsid: 414,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Info Air Control-3",
    ROLEID: 1,
    Documentpath: "Admin/ATCO/DL Info Singapore-071223",
  },
  {
    SerialN: 28,
    Stafftype: null,
    document: "Cab Control 102.pdf",
    DocumentArea: "Info Notice",
    AREAID: 2,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:59:11",
    Unreadcount: 0,
    uploadeddocumentsid: 415,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Info Air Control-4",
    ROLEID: 1,
    Documentpath: "Admin/ATCO/DL Info Singapore-071223",
  },
  {
    SerialN: 29,
    Stafftype: null,
    document: "Cab Control 101.pdf",
    DocumentArea: "Info Notice",
    AREAID: 2,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:59:11",
    Unreadcount: 0,
    uploadeddocumentsid: 416,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Info Air Control-5",
    ROLEID: 1,
    Documentpath: "Admin/ATCO/DL Info Singapore-071223",
  },
  {
    SerialN: 30,
    Stafftype: null,
    document: "Cab Control 105.pdf",
    DocumentArea: "Info Notice",
    AREAID: 2,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:59:11",
    Unreadcount: 0,
    uploadeddocumentsid: 417,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Info Air Control-1",
    ROLEID: 1,
    Documentpath: "Admin/ATCO/DL Info Singapore-071223",
  },
  {
    SerialN: 31,
    Stafftype: null,
    document: "Cab Control 104.pdf",
    DocumentArea: "Info Notice",
    AREAID: 2,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:59:11",
    Unreadcount: 0,
    uploadeddocumentsid: 418,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Info Air Control-2",
    ROLEID: 1,
    Documentpath: "Admin/ATCO/DL Info Singapore-071223",
  },
  {
    SerialN: 32,
    Stafftype: null,
    document: "Air9.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:57:28",
    Unreadcount: 38,
    uploadeddocumentsid: 412,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Ed Air Control-1 new123",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/DL-Singapore-071223",
  },
  {
    SerialN: 33,
    Stafftype: null,
    document: "Cab Control 102.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:57:28",
    Unreadcount: 0,
    uploadeddocumentsid: 413,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Ed Air Control-4",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/DL-Singapore-071223",
  },
  {
    SerialN: 34,
    Stafftype: null,
    document: "Air11-New.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:57:28",
    Unreadcount: 0,
    uploadeddocumentsid: 433,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Ed Air Control-5",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/DL-Singapore-071223",
  },
  {
    SerialN: 35,
    Stafftype: null,
    document: "CAR_Part_11e-23June08.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:57:28",
    Unreadcount: 0,
    uploadeddocumentsid: 410,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Ed Air Control-2 new12",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/DL-Singapore-071223",
  },
  {
    SerialN: 36,
    Stafftype: null,
    document: "TrainingDetails.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:30:03",
    Unreadcount: 19,
    uploadeddocumentsid: 379,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Mid Test-052",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M7     ",
  },
  {
    SerialN: 37,
    Stafftype: null,
    document: "Circular_(COVID-19)_In-Flight_Announcement.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 10:06:26",
    Unreadcount: 0,
    uploadeddocumentsid: 443,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Mid Air__Control--082",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M2     ",
  },
  {
    SerialN: 38,
    Stafftype: null,
    document: "The basic form of administrative punishment ar.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 09:51:22",
    Unreadcount: 0,
    uploadeddocumentsid: 442,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "The Unicode standard solves the encoding dete1",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M2     ",
  },
  {
    SerialN: 39,
    Stafftype: null,
    document: "Air Control _21-08-2020.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 09:17:52",
    Unreadcount: 763,
    uploadeddocumentsid: 441,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Mid Air_Control-081",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M2     ",
  },
  {
    SerialN: 40,
    Stafftype: null,
    document: "35-21_93REV03.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "Tayde(SWP60174)",
    UploadedOn: "08-Dec-2023 07:41:54",
    Unreadcount: 0,
    uploadeddocumentsid: 440,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Nilesh Test 8Dec",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/460",
  },
  {
    SerialN: 41,
    Stafftype: 0,
    document: "ASMS_SWP_Mid_Area_Section5624.pdf",
    DocumentArea: "Group Memos",
    AREAID: 7,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "08-Dec-2023 07:04:29",
    Unreadcount: 4,
    uploadeddocumentsid: 439,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "gpfile1tr23456",
    ROLEID: 1,
    Documentpath: "ADMIN/GROUPMEMOS/gp123456",
  },
  {
    SerialN: 42,
    Stafftype: 0,
    document: "ASMS_SWP_Mid_Area_Section56.pdf",
    DocumentArea: "Group Memos",
    AREAID: 7,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "08-Dec-2023 06:57:15",
    Unreadcount: 4,
    uploadeddocumentsid: 438,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "gpfile123456",
    ROLEID: 1,
    Documentpath: "Admin/GROUPMEMOS/",
  },
  {
    SerialN: 43,
    Stafftype: null,
    document: "Cab5.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 06:36:51",
    Unreadcount: 17,
    uploadeddocumentsid: 434,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Ed_Note-082",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/DL-Singapore-071223/Ed Note-081",
  },
  {
    SerialN: 44,
    Stafftype: null,
    document: "Cab6.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "08-Dec-2023 06:36:51",
    Unreadcount: 0,
    uploadeddocumentsid: 436,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Ed Note 083",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/DL-Singapore-071223/Ed Note-081",
  },
  {
    SerialN: 45,
    Stafftype: null,
    document: "ASMS_SWP_Mid_Area_Section12.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "08-Dec-2023 06:01:23",
    Unreadcount: 0,
    uploadeddocumentsid: 437,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "file08dec20231",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M6     ",
  },
  {
    SerialN: 46,
    Stafftype: null,
    document: "Air10.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "07-Dec-2023 13:23:52",
    Unreadcount: 0,
    uploadeddocumentsid: 432,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: " MID TEST-072",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M7     ",
  },
  {
    SerialN: 47,
    Stafftype: null,
    document: "Air111.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "07-Dec-2023 11:25:03",
    Unreadcount: 763,
    uploadeddocumentsid: 426,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "ed test-101 new",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/Notams_Test-211123",
  },
  {
    SerialN: 48,
    Stafftype: null,
    document: "LAI-IN_EWF Loan Appl Form-R1c (Form)- Nikhil.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "07-Dec-2023 11:22:36",
    Unreadcount: 0,
    uploadeddocumentsid: 368,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "ABC new",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/Notams_Test-211123",
  },
  {
    SerialN: 49,
    Stafftype: null,
    document: "Test 6.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "NIKHIL HEDUKAR(SWP60164)",
    UploadedOn: "07-Dec-2023 11:18:50",
    Unreadcount: 1,
    uploadeddocumentsid: 93,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "P Air Test-202- 20MB",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/896",
  },
  {
    SerialN: 50,
    Stafftype: null,
    document: "Test 6.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "NIKHIL HEDUKAR(SWP60164)",
    UploadedOn: "07-Dec-2023 11:18:29",
    Unreadcount: 1,
    uploadeddocumentsid: 425,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "Sample 1",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/978",
  },
  {
    SerialN: 51,
    Stafftype: null,
    document: "Air Control 121.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "NIKHIL HEDUKAR(SWP60164)",
    UploadedOn: "07-Dec-2023 10:51:40",
    Unreadcount: 0,
    uploadeddocumentsid: 286,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Ed test 211GGG",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/Notams_Test-211123",
  },
  {
    SerialN: 52,
    Stafftype: null,
    document: "Cab Control 103.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "NIKHIL HEDUKAR(SWP60164)",
    UploadedOn: "07-Dec-2023 10:51:40",
    Unreadcount: 762,
    uploadeddocumentsid: 288,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Ed_Test-213SSS",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/Notams_Test-211123",
  },
  {
    SerialN: 53,
    Stafftype: null,
    document: "ASMS_SWP_Mid_Area_Section.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "Admin R(AD001)",
    UploadedOn: "07-Dec-2023 08:56:30",
    Unreadcount: 1,
    uploadeddocumentsid: 424,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "riteshfile1234",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/ATCO/973",
  },
  {
    SerialN: 54,
    Stafftype: null,
    document: "ASMS_SWP_Mid_Area_Section.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "07-Dec-2023 08:41:22",
    Unreadcount: 762,
    uploadeddocumentsid: 423,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "file notom123",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M6     ",
  },
  {
    SerialN: 55,
    Stafftype: null,
    document: "Portable_Oxygen_Cylinder_in_ATR-72-600.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "07-Dec-2023 07:29:59",
    Unreadcount: 0,
    uploadeddocumentsid: 422,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "P Test-071",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/996",
  },
  {
    SerialN: 56,
    Stafftype: null,
    document: "Air-7_M.12.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "07-Dec-2023 06:40:03",
    Unreadcount: 37,
    uploadeddocumentsid: 420,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Mid Test-072",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M7     ",
  },
  {
    SerialN: 57,
    Stafftype: null,
    document: "38-34_12REV07.PDF",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "Tayde(SWP60174)",
    UploadedOn: "07-Dec-2023 05:51:32",
    Unreadcount: 1,
    uploadeddocumentsid: 419,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "PM 7Dec Nilesh New Entry",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/852",
  },
  {
    SerialN: 58,
    Stafftype: null,
    document: "Air Control 119.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "07-Dec-2023 05:20:33",
    Unreadcount: 18,
    uploadeddocumentsid: 409,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Mid Test-071",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M7     ",
  },
  {
    SerialN: 59,
    Stafftype: null,
    document: "TableData (3).pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "06-Dec-2023 14:06:24",
    Unreadcount: 25,
    uploadeddocumentsid: 399,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Doc431",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M3     ",
  },
  {
    SerialN: 60,
    Stafftype: null,
    document: "AIR CONTROL-01-08-2020.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "06-Dec-2023 12:21:00",
    Unreadcount: 1,
    uploadeddocumentsid: 408,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "P Test-061",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/1004",
  },
  {
    SerialN: 61,
    Stafftype: null,
    document: "TempProject_20231129_181328_links.php.txt",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "06-Dec-2023 10:23:45",
    Unreadcount: 1,
    uploadeddocumentsid: 406,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "test",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/2",
  },
  {
    SerialN: 62,
    Stafftype: null,
    document: "TempProject_20231129_181328_links.php.txt",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "06-Dec-2023 10:22:13",
    Unreadcount: 1,
    uploadeddocumentsid: 405,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "test",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/927",
  },
  {
    SerialN: 63,
    Stafftype: null,
    document: "TempProject_20231129_181328_links.php.txt",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "06-Dec-2023 10:19:36",
    Unreadcount: 1,
    uploadeddocumentsid: 404,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "test",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/217",
  },
  {
    SerialN: 64,
    Stafftype: null,
    document: "TempProject_20231129_181328_links.txt",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "06-Dec-2023 10:17:51",
    Unreadcount: 1,
    uploadeddocumentsid: 403,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "test",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/407",
  },
  {
    SerialN: 65,
    Stafftype: null,
    document: "TableData.csv",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "06-Dec-2023 10:16:26",
    Unreadcount: 1,
    uploadeddocumentsid: 402,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "test",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/574",
  },
  {
    SerialN: 66,
    Stafftype: null,
    document: "TableData (2).pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "06-Dec-2023 09:43:00",
    Unreadcount: 762,
    uploadeddocumentsid: 400,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Doc0",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M4     ",
  },
  {
    SerialN: 67,
    Stafftype: null,
    document: "OpTransactionHistoryTpr28-10-2023.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "06-Dec-2023 09:37:06",
    Unreadcount: 762,
    uploadeddocumentsid: 398,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Dock9",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M3     ",
  },
  {
    SerialN: 68,
    Stafftype: null,
    document: "Test10MB_Oct.txt",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "06-Dec-2023 09:26:06",
    Unreadcount: 10,
    uploadeddocumentsid: 182,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "ed test note-032",
    ROLEID: 1,
    Documentpath:
      "Admin/e-DOCS CENTER/ATCO/Civil Aviation Aurhority of India-03-Oct-23/ed note-1",
  },
  {
    SerialN: 69,
    Stafftype: null,
    document: "TableData (2).pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "06-Dec-2023 09:20:35",
    Unreadcount: 762,
    uploadeddocumentsid: 397,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "DC",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M3     ",
  },
  {
    SerialN: 70,
    Stafftype: null,
    document: "I-Accept.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "06-Dec-2023 09:16:54",
    Unreadcount: 762,
    uploadeddocumentsid: 396,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Dock",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M3     ",
  },
  {
    SerialN: 71,
    Stafftype: null,
    document: "companylogo.png",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "06-Dec-2023 09:08:58",
    Unreadcount: 763,
    uploadeddocumentsid: 395,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Doc65",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M3     ",
  },
  {
    SerialN: 72,
    Stafftype: null,
    document: "ATSM - React.pptx",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "06-Dec-2023 09:04:24",
    Unreadcount: 762,
    uploadeddocumentsid: 394,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "6thdec4",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M3     ",
  },
  {
    SerialN: 73,
    Stafftype: null,
    document: "_John_Doerr__Measure_What_Matters_z-lib.org_1.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "06-Dec-2023 08:55:44",
    Unreadcount: 762,
    uploadeddocumentsid: 393,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Doc43",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M4     ",
  },
  {
    SerialN: 74,
    Stafftype: null,
    document: "TableData.php.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "06-Dec-2023 07:12:05",
    Unreadcount: 762,
    uploadeddocumentsid: 388,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "6thdec3",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M4     ",
  },
  {
    SerialN: 75,
    Stafftype: null,
    document: "Test 2.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "SUBODH PATIL(SP60161)",
    UploadedOn: "06-Dec-2023 06:41:38",
    Unreadcount: 0,
    uploadeddocumentsid: 309,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Test File 1",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M3     ",
  },
  {
    SerialN: 76,
    Stafftype: null,
    document: "COVID_VACCINATION212.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "06-Dec-2023 06:40:05",
    Unreadcount: 1,
    uploadeddocumentsid: 392,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "ttttt",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/173",
  },
  {
    SerialN: 77,
    Stafftype: null,
    document: "COVID_VACCINATION212.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "06-Dec-2023 06:33:25",
    Unreadcount: 762,
    uploadeddocumentsid: 391,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "notam file 7",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M6     ",
  },
  {
    SerialN: 78,
    Stafftype: null,
    document: "COVID_VACCINATION21.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "06-Dec-2023 06:29:12",
    Unreadcount: 761,
    uploadeddocumentsid: 390,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "notam file 6",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M6     ",
  },
  {
    SerialN: 79,
    Stafftype: null,
    document: "COVID_VACCINATION1234.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "06-Dec-2023 06:28:01",
    Unreadcount: 32,
    uploadeddocumentsid: 389,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "notam file 12345",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M6     ",
  },
  {
    SerialN: 80,
    Stafftype: null,
    document: "COVID_VACCINATION123.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "06-Dec-2023 06:07:44",
    Unreadcount: 764,
    uploadeddocumentsid: 387,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "notam 05dec file2",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M6     ",
  },
  {
    SerialN: 81,
    Stafftype: null,
    document: "LAI TSP NG Program Charter.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "06-Dec-2023 06:06:39",
    Unreadcount: 763,
    uploadeddocumentsid: 386,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "6thdec",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M3     ",
  },
  {
    SerialN: 82,
    Stafftype: null,
    document: "COVID_VACCINATION12.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "RITESH TRIVEDI(SWP60160)",
    UploadedOn: "06-Dec-2023 06:03:29",
    Unreadcount: 764,
    uploadeddocumentsid: 385,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "notam file 05 dec",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M6     ",
  },
  {
    SerialN: 83,
    Stafftype: null,
    document: "www.rediff.com",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "AKSHADA MOGHE(SWP60163)",
    UploadedOn: "05-Dec-2023 13:13:38",
    Unreadcount: 0,
    uploadeddocumentsid: 384,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "sadsad",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M4     ",
  },
  {
    SerialN: 84,
    Stafftype: null,
    document: "TableData.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "05-Dec-2023 12:57:54",
    Unreadcount: 0,
    uploadeddocumentsid: 382,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "ttim",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M5     ",
  },
  {
    SerialN: 85,
    Stafftype: null,
    document: "35-21-_99REV01.PDF",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Tayde(SWP60174)",
    UploadedOn: "05-Dec-2023 12:50:09",
    Unreadcount: 10,
    uploadeddocumentsid: 383,
    Ismustread: true,
    PartyTypeID: 2,
    Documentname: "ATCSO M5 File Rpt",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCSO/M5     ",
  },
  {
    SerialN: 86,
    Stafftype: null,
    document: "TableData.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "05-Dec-2023 12:22:06",
    Unreadcount: 0,
    uploadeddocumentsid: 381,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "estim",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M7     ",
  },
  {
    SerialN: 87,
    Stafftype: null,
    document: "You may already have a lot of You may already1.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "05-Dec-2023 12:08:52",
    Unreadcount: 84,
    uploadeddocumentsid: 371,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Mid Test-051",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M7     ",
  },
  {
    SerialN: 88,
    Stafftype: null,
    document: "Cab20.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "05-Dec-2023 10:52:44",
    Unreadcount: 0,
    uploadeddocumentsid: 372,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "Mid Test-52",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M7     ",
  },
  {
    SerialN: 89,
    Stafftype: null,
    document: "TableData (11).pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "05-Dec-2023 10:29:32",
    Unreadcount: 0,
    uploadeddocumentsid: 378,
    Ismustread: false,
    PartyTypeID: 2,
    Documentname: "Test05Dec",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCSO/M3     ",
  },
  {
    SerialN: 90,
    Stafftype: null,
    document: "35-22-26REV011.PDF",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "Tayde(SWP60174)",
    UploadedOn: "05-Dec-2023 09:17:01",
    Unreadcount: 1,
    uploadeddocumentsid: 377,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "PM ABH 05Dec",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/173",
  },
  {
    SerialN: 91,
    Stafftype: null,
    document: "35-10_71_REV02.PDF",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Tayde(SWP60174)",
    UploadedOn: "05-Dec-2023 07:50:35",
    Unreadcount: 160,
    uploadeddocumentsid: 375,
    Ismustread: true,
    PartyTypeID: 2,
    Documentname: "ATCSO M5 File1",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCSO/M5     ",
  },
  {
    SerialN: 92,
    Stafftype: null,
    document: "35-22-26REV011.PDF",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Tayde(SWP60174)",
    UploadedOn: "05-Dec-2023 07:47:05",
    Unreadcount: 162,
    uploadeddocumentsid: 376,
    Ismustread: true,
    PartyTypeID: 2,
    Documentname: "ATCSO M5 File2",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCSO/M5     ",
  },
  {
    SerialN: 93,
    Stafftype: null,
    document:
      "Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7 Test 7.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "NIKHIL HEDUKAR(SWP60164)",
    UploadedOn: "05-Dec-2023 06:49:47",
    Unreadcount: 0,
    uploadeddocumentsid: 374,
    Ismustread: false,
    PartyTypeID: 1,
    Documentname: "x",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/KKK_TT1111",
  },
  {
    SerialN: 94,
    Stafftype: null,
    document: "AIR_CONTROL-01-08-2020.pdf",
    DocumentArea: "E-Docs Center",
    AREAID: 1,
    PartyName: "NIKHIL HEDUKAR(SWP60164)",
    UploadedOn: "04-Dec-2023 12:07:34",
    Unreadcount: 760,
    uploadeddocumentsid: 207,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "ed air note-202",
    ROLEID: 1,
    Documentpath: "Admin/e-DOCS CENTER/ATCO/Notams_Test-20OCT23/Note-1",
  },
  {
    SerialN: 95,
    Stafftype: null,
    document: "Air211.pdf",
    DocumentArea: "Mid Area",
    AREAID: 4,
    PartyName: "Admin R(AD001)",
    UploadedOn: "04-Dec-2023 07:45:47",
    Unreadcount: 758,
    uploadeddocumentsid: 361,
    Ismustread: true,
    PartyTypeID: 1,
    Documentname: "Mid Test-0412",
    ROLEID: 1,
    Documentpath: "Admin/Mid Area/ATCO/M7     ",
  },
  {
    SerialN: 96,
    Stafftype: null,
    document: "Air11-New.pdf",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "MAHESH LAKAL(ML6016)",
    UploadedOn: "04-Dec-2023 06:29:20",
    Unreadcount: 0,
    uploadeddocumentsid: 354,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "P Test-015 new",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/996",
  },
  {
    SerialN: 97,
    Stafftype: null,
    document: "35-10_71_REV02.PDF",
    DocumentArea: "Personal Memos",
    AREAID: 6,
    PartyName: "Tayde(SWP60174)",
    UploadedOn: "04-Dec-2023 04:54:17",
    Unreadcount: 1,
    uploadeddocumentsid: 359,
    Ismustread: false,
    PartyTypeID: 0,
    Documentname: "04DEC  Nilesh",
    ROLEID: 1,
    Documentpath: "ADMIN/PERSONALMEMOS/983",
  },
];
